name: carmelitas_dormitory_system

description: "CarmeLink dormitory management app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.17.1
  supabase_flutter: ^2.17.2
  geolocator: ^14.0.3
  pdf: ^3.13.1
  printing: ^5.15.1
  file_picker: ^13.1.0
  crypto: ^3.0.7
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/images/
    - assets/web/brand/
    - assets/web/photos/
  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/carmelita_logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/carmelita_logo.jpg"
  remove_alpha_ios: true
